### ISSUE TITLE
Subobjects in Config

### ISSUE THREAD

**Issue by cornerman** [protontypes/openselery#96]
For more consistency within the configuration yml.

We could introduce sub-objects for some options to better work with dependent variables.

Exmple `split_mode`.

```yaml
split_mode:
  type: "random"
  ## the amount of btc send per user at random_split
  btc_per_transaction: 0.000002
```

```yaml
split_mode:
  type: "full"
```

Currently btc_per_transaction just does nothing in `split_mode=full` and only works in `split_mode=random`.
